version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: src/Todolist.WebAPI/Dockerfile
    image: todolist:latest 
    ports:
      - "8080:8080" 
      - "8081:8081" 
    environment:
      - ConnectionStrings__DefaultConnection=Server=sqlserver;Database=TodoDb;User Id=sa;Password=Todo@Passw0rd;TrustServerCertificate=True; 
    depends_on:
      - sqlserver
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - SA_PASSWORD=Todo@Passw0rd
      - ACCEPT_EULA=Y
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql

volumes:
  sql_data:
